[env:esp32-s3-matrix]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 4MB
board_build.flash_mode = qio
board_build.partitions = default.csv

lib_deps =
    fastled/FastLED@^3.7.1

build_flags =
    -D MATRIX_W=8
    -D MATRIX_H=8
    -D LED_PIN=14
    -D BRIGHTNESS=20
    -D ARDUINO_USB_CDC_ON_BOOT=1
